### ISSUE TITLE
CudaFDKConeBeamReconstructionFilter Execute not working, driver problem?

### ISSUE THREAD

**Issue by EmmanuelleRicher** [RTKConsortium/RTK#190]
Hi, 

I'm trying to use SimpleRTK to make a 3D reconstruction of cone beam projections. I'm using PyCharm (SimpleRTK was successfully builded and the package installed on Python). I succeeded with the CPU methods and am now trying to use the same code with the GPU using methods to make it faster (for example CudaFDKConeBeamReconstructionFilter instead of FDKConeBeamReconstructionFilter ). I received an error:

Traceback (most recent call last):
  File "C:\RootReferences\OrsQtPlateform\python\OrsPythonPlugins\OrsReconstruction\mainform.py", line 155, in on_PushButton_apply_clicked
    srtkImage = feldkamp.Execute(imageRecons, srtkData)
  File "C:\Anaconda3\Lib\site-packages\SimpleRTK\SimpleRTK.py", line 7972, in Execute
    return _SimpleRTK.CudaFDKConeBeamReconstructionFilter_Execute(self, *args)
RuntimeError: Exception thrown in SimpleRTK CudaFDKConeBeamReconstructionFilter_Execute: C:\Users\admin\Desktop\RTK-1.4.0\utilities\ITKCudaCommon\include\itkCudaDataManager.h:54:
Cuda Error : CUDA driver version is insufficient for CUDA runtime version.

I am relatively new to programming and can't seem to understand this error. Do you know what I should do to make the methods work? Is it a problem in my code or really a driver problem? I can publish a bit of my code if it helps.

Thank you, 
Emmanuelle Richer

**Comment by EmmanuelleRicher** [comment]
The problem was my Nvidia driver version, I updated it and now everything works!
