### ISSUE TITLE
Conflict between module ITKRegistrationCommonPython and RTK ?

### ISSUE THREAD

**Issue by arobert01** [RTKConsortium/RTK#390]
Hello, 

When I tried to use filters from the module _itk.ITKRegistrationCommonPython_ in Python I got this error:

```
Traceback (most recent call last):

  File "/export/home/arobert/Documents/code/src/algo/registration.py", line 13, in <module>
    trans_registration = itk.ImageRegistrationMethodv4[image_type, image_type].New()
  File "/export/home/arobert/.local/lib/python3.6/site-packages/itkLazy.py", line 52, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "/export/home/arobert/.local/lib/python3.6/site-packages/itkBase.py", line 91, in LoadModule
    LoadModule(dep, namespace)
  File "/export/home/arobert/.local/lib/python3.6/site-packages/itkBase.py", line 91, in LoadModule
    LoadModule(dep, namespace)
  File "/export/home/arobert/.local/lib/python3.6/site-packages/itkBase.py", line 61, in LoadModule
    swig.update(this_module.swig)
AttributeError: module 'itk.ITKRegistrationCommonPython' has no attribute 'swig'
```

I found out that instantiate a RTK filter before using the ITK filter fixed this error. Another way to get rid of this error is to uninstall the package python _itk-rtk_ (not really convenient).

You can use the following code to reproduce this behavior:

```   
import itk
from itk import RTK as rtk

image_type = itk.Image[itk.F,2]
#osem = rtk.OSEMConeBeamReconstructionFilter.New()
trans_registration = itk.ImageRegistrationMethodv4[image_type, image_type].New()
```

I'am using the itk-rtk package generated [here](https://github.com/SimonRit/RTK/actions/runs/341384403) on Linux with Python 3.6.

Thanks.

**Comment by axel-grc** [comment]
Closing as no longer reproducible: the conflicting itkBase.py/itkLazy.py lazy-loading code was rewritten into the itk.support.* package in ITK 5.2, so the swig.update() error path no longer exists and doesn't occur with current itk-rtk releases.
